### ISSUE TITLE
Action doesn't support headers linking to github releases

### ISSUE THREAD

**Issue by Jibbajabbafic** [thomaseizinger/keep-a-changelog-new-release#12]
I like to use the following format in the footer of my changelog so my release headers link to the github release pages themselves, but this doesn't appear to be supported with this action:
```md
[Unreleased]: https://github.com/foo/bar/compare/v0.0.2...HEAD
[0.0.2]: https://github.com/foo/bar/releases/tag/v0.0.2
[0.0.1]: https://github.com/foo/bar/releases/tag/v0.0.1
```
When I run the action I get the following error:
```
Run thomaseizinger/keep-a-changelog-new-release@1.3.0
(node:1591) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: Invalid changelog format, compare url is not standard
```
### Action code:
```
      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          tag: ${{ github.ref_name }}
```

Is this something you would be able to support in future? Perhaps by detecting the format and using it automatically.

**Comment by thomaseizinger** [comment]
The idea of the compare URL (as per spec: https://keepachangelog.com/en/1.0.0/) is to provide people with an overview of what code changed between two versions.

I never considered supporting anything outside of that, nor have I ever seen linking to the actual release. I am not opposed to it but the spec also mentions that the changelog itself is more of an alternative to GitHub releases rather and a complement. What is the value of linking to the GitHub release if all the information should arguable already be in the changelog? What do users discover there that they can't see in the changelog?

**Comment by Jibbajabbafic** [comment]
I've been thinking it over and I might just switch to follow it exactly as it's such a minor change. Like I said it was just a personal preference.

I quite liked how the initial release linked directly to the download page and my thinking at the time was that was more intuitive to users, as I wouldn't think most people are interested in the git logs (that's why we have a changelog!).

It would be much appreciated if you'd still like to support custom link formats, but I certainly don't expect it.
Many thanks for providing this extension either way!

**Comment by thomaseizinger** [comment]
I am glad it works for you :)

I'll close this then. If someone else needs custom link formats at some point, we can discuss that either here or in a new issue!
