### ISSUE TITLE
Deprecated node12

### ISSUE THREAD

**Issue by MarkoSagadin** [thomaseizinger/keep-a-changelog-new-release#18]
Hello,

I have been a happy user of your Github Action on several projects!

I have noticed some time ago that my workflows started emitting an warning related to the deprecation of the node12:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, thomaseizinger/keep-a-changelog-new-release@1.3.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

I am super familiar with javascript and typescript, but I could take a look at the issue.

Could you give me some hints where should I start looking?

I can see that `action.yaml` specifies node12, but there are also packages in the `pacakge.json` file that probably need to be updated.

**Comment by MarkoSagadin** [comment]
I have forked the repo, updated `node12` to `node16` in `actions.yml` and ran the action from my test repo. 
The warning disappeared. 

From outside it seem that this is all that needs to be done, but I believe that probably some more work is needed.

**Comment by baynezy** [comment]
Is there any progress on this?

**Comment by thomaseizinger** [comment]
> I have forked the repo, updated `node12` to `node16` in `actions.yml` and ran the action from my test repo.
> The warning disappeared.

A PR needs to be created that makes this change.

**Comment by MarkoSagadin** [comment]
@thomaseizinger A PR was created.

**Comment by thomaseizinger** [comment]
You should be able to reference the action now using the latest hash from master. If everything works as expected, I am happy to make a release after.

**Comment by MarkoSagadin** [comment]
Hi @thomaseizinger, I have tested the commit, everything works as expected. You can make a release :)

**Comment by thomaseizinger** [comment]
> Hi @thomaseizinger, I have tested the commit, everything works as expected. You can make a release :)

Sorry for the excessively long wait. This is now released as v2.
