### ISSUE TITLE
Update remark-parse version to fix security vulnerability

### ISSUE THREAD

**Issue by danimanrique-jt** [thomaseizinger/keep-a-changelog-new-release#26]
👋🏼 Hey @thomaseizinger!
Nice to meet you!

I am using your action to update the app's CHANGELOG but I found there is a high-security vulnerability on one of the dependencies (remark-parse) you are using as you can see in this security report from the [Synk](https://snyk.io/) tool:

![CleanShot 2024-04-16 at 13 58 54@2x](https://github.com/thomaseizinger/keep-a-changelog-new-release/assets/108278833/c32cd7d9-c946-4b29-8352-c50686b87f31)

I would like to keep using your action, but for that, it is mandatory that this vulnerability be fixed. Could we do a quick update on this dependency to the 9.0.0 version?

Thanks in advance 🙂

**Comment by thomaseizinger** [comment]
> I would like to keep using your action, but for that, it is mandatory that this vulnerability be fixed. Could we do a quick update on this dependency to the 9.0.0 version?

SUre! PRs welcome!
